// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5QQ18IBT_bfBnQwIC1NlvhbFrk56ndg',
    appId: '1:1069408095069:web:cabd50a9dfdcdcdf17b6b4',
    messagingSenderId: '1069408095069',
    projectId: 'ecommerceapp-bf4ce',
    authDomain: 'ecommerceapp-bf4ce.firebaseapp.com',
    storageBucket: 'ecommerceapp-bf4ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdp-jZr8iSvvtXl8UFrYdsj6fK4xverI',
    appId: '1:1069408095069:android:bdb406afc13fa71917b6b4',
    messagingSenderId: '1069408095069',
    projectId: 'ecommerceapp-bf4ce',
    storageBucket: 'ecommerceapp-bf4ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7i8t9_YeqElrKSf697l3AuHl6tvtktXE',
    appId: '1:1069408095069:ios:45891d19bce5428717b6b4',
    messagingSenderId: '1069408095069',
    projectId: 'ecommerceapp-bf4ce',
    storageBucket: 'ecommerceapp-bf4ce.firebasestorage.app',
    androidClientId: '1069408095069-l4dq92gh31q09vesb7hm030aan1m90e1.apps.googleusercontent.com',
    iosClientId: '1069408095069-7bvfkckm7chpak42fkhl78ihep0rj564.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7i8t9_YeqElrKSf697l3AuHl6tvtktXE',
    appId: '1:1069408095069:ios:45891d19bce5428717b6b4',
    messagingSenderId: '1069408095069',
    projectId: 'ecommerceapp-bf4ce',
    storageBucket: 'ecommerceapp-bf4ce.firebasestorage.app',
    androidClientId: '1069408095069-l4dq92gh31q09vesb7hm030aan1m90e1.apps.googleusercontent.com',
    iosClientId: '1069408095069-7bvfkckm7chpak42fkhl78ihep0rj564.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD5QQ18IBT_bfBnQwIC1NlvhbFrk56ndg',
    appId: '1:1069408095069:web:ab5e0df73ebb3d8017b6b4',
    messagingSenderId: '1069408095069',
    projectId: 'ecommerceapp-bf4ce',
    authDomain: 'ecommerceapp-bf4ce.firebaseapp.com',
    storageBucket: 'ecommerceapp-bf4ce.firebasestorage.app',
  );

}